# Generated by Django 4.1.4 on 2022-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worsst", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
