# Generated by Django 4.1.4 on 2022-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worsst", "0002_alter_feed_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrycontent",
            name="content",
            field=models.TextField(),
        ),
    ]
