# Generated by Django 3.2.9 on 2022-04-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
