# Generated by Django 3.2.9 on 2022-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.IntegerField(
                choices=[(0, "draft"), (1, "published")], default=0
            ),
        ),
    ]
