# Generated by Django 3.2.9 on 2022-05-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogimage",
            name="alt_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
