# Generated by Django 3.2.9 on 2023-02-27 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("til", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tidbit",
            name="date",
        ),
        migrations.AddField(
            model_name="tidbit",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
