# Generated by Django 3.2.9 on 2022-03-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
