# Generated by Django 3.2.9 on 2022-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_journal", "0002_alter_recipe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipe_journal/recipe_images/"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("photo__isnull", False), ("url__isnull", True)),
                    models.Q(("photo__isnull", True), ("url__isnull", False)),
                    _connector="OR",
                ),
                name="photo_or_url",
            ),
        ),
    ]
