# Generated by Django 3.2.9 on 2022-03-29 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_journal", "0003_auto_20220329_1546"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipe",
            name="photo_or_url",
        ),
    ]
