# Generated by Django 3.2.9 on 2021-12-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yesman", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yesitem",
            name="completed",
            field=models.DateTimeField(),
        ),
    ]
