# Generated by Django 3.2.9 on 2021-12-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yesman", "0002_alter_yesitem_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yesitem",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
