# Generated by Django 4.1.9 on 2024-07-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('position_accuracy', models.FloatField()),
                ('altitude', models.FloatField()),
                ('altitude_accuracy', models.FloatField()),
                ('heading', models.FloatField()),
                ('speed', models.FloatField()),
            ],
        ),
    ]
