# Generated by Django 3.2.9 on 2022-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_budgetlimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetlimit",
            name="edited_category",
            field=models.CharField(
                choices=[
                    ("big", "Big Purchases"),
                    ("car", "Car"),
                    ("cof", "Coffee"),
                    ("fnf", "Fun Food"),
                    ("fns", "Fun Shopping"),
                    ("gro", "Groceries"),
                    ("med", "Medical Services"),
                    ("nos", "Normal Shopping"),
                    ("qum", "Quick Meal"),
                    ("res", "Restaurants"),
                    ("sub", "Subscriptions/Donations"),
                    ("trn", "Transit"),
                    ("trv", "Travel"),
                    ("utl", "Utilities"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
    ]
