# Generated by Django 3.2.9 on 2022-09-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budgetlimit_edited_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetLimit',
            new_name='MonthlyLimit',
        ),
    ]
