# Generated by Django 3.2.7 on 2021-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0002_glist_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glist",
            name="is_active",
        ),
        migrations.AddField(
            model_name="glistitem",
            name="gotten",
            field=models.BooleanField(default=True),
        ),
    ]
