# Generated by Django 3.2.7 on 2021-09-30 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0005_alter_trip_glist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glistitem",
            options={"ordering": ["order_in_list"]},
        ),
    ]
