# Generated by Django 3.2.7 on 2021-09-30 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0006_alter_glistitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glistitem",
            options={},
        ),
    ]
