# Generated by Django 3.2.9 on 2022-09-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0008_glist_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glist',
            name='groceries',
        ),
        migrations.RemoveField(
            model_name='glistitem',
            name='glist',
        ),
        migrations.RemoveField(
            model_name='glistitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='glist',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='store',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='unlisted_groceries',
        ),
        migrations.DeleteModel(
            name='AisleLocation',
        ),
        migrations.DeleteModel(
            name='GList',
        ),
        migrations.DeleteModel(
            name='GListItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
