# Generated by Django 4.1.9 on 2025-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0010_glist"),
    ]

    operations = [
        migrations.AddField(
            model_name="glist",
            name="checked_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
