# Generated by Django 3.2.9 on 2022-01-06 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pixart", models.FileField(upload_to="pixart/pixart/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="pixart/thumbnails/"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="SaveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statuses", models.TextField()),
                ("progress", models.FloatField()),
                (
                    "art_piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelart.artpiece",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
