# Generated by Django 3.2.9 on 2022-01-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pixelart", "0002_auto_20220106_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedata",
            name="progress",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedata",
            name="statuses",
            field=models.TextField(blank=True, null=True),
        ),
    ]
