# Generated by Django 3.2.9 on 2022-01-07 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pixelart", "0004_artpiece_filled_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artpiece",
            options={"ordering": ["-created"]},
        ),
    ]
