# Generated by Django 4.1.9 on 2024-08-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_alter_search_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['timestamp']},
        ),
    ]
