# Generated by Django 3.2.9 on 2022-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingman", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inginstance",
            old_name="is_active",
            new_name="exists",
        ),
        migrations.AlterField(
            model_name="inginstance",
            name="created",
            field=models.DateTimeField(),
        ),
    ]
