# Generated by Django 3.2.9 on 2022-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingman", "0002_auto_20220519_1007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredienttype",
            name="category",
            field=models.CharField(
                choices=[
                    ("PR", "Produce"),
                    ("DA", "Dairy"),
                    ("ME", "Meat"),
                    ("BR", "Bread"),
                    ("FR", "Frozen"),
                    ("PA", "Pantry"),
                    ("HO", "Household"),
                    ("PF", "Prepared Foods"),
                ],
                max_length=2,
            ),
        ),
    ]
